fragment GlobalParts on Global {
  __typename
  site {
    __typename
    title
    logoText
    contactEmail
    navigation {
      __typename
      links {
        __typename
        label
        href
      }
    }
    footer {
      __typename
      content
    }
  }
}

fragment PageParts on Page {
  __typename
  title
  metaTitle
  metaDescription
  hero {
    __typename
    badge
    title
    subtitle
    stats {
      __typename
      number
      label
    }
    cta {
      __typename
      text
      href
    }
  }
  services {
    __typename
    badge
    title
    subtitle
    serviceCards {
      __typename
      name
      subtitle
      description
      features
    }
  }
  process {
    __typename
    title
    subtitle
    steps {
      __typename
      number
      title
      description
    }
  }
  about {
    __typename
    title
    content
  }
  contact {
    __typename
    title
    subtitle
    form {
      __typename
      submitText
      successMessage
    }
  }
}

fragment BlogParts on Blog {
  __typename
  title
  date
  author
  featuredImage
  excerpt
  content
  categories
  seoTitle
  seoDescription
}
